### PR TITLE
WASAPI: Correctly handle no input or output devices instead of crashing.

### LINKED ISSUE #63: WASAPI backend: Libsoundio closes the program when no microphone is connected
In wsapi.c on line 694:

`if (FAILED(hr = IMMDeviceEnumerator_GetDefaultAudioEndpoint(siw->device_enumerator, eCapture,
                    eMultimedia, &rd.default_capture_device)))`

This command always fails if no microphone is connected at all. This leads to the program crashing on the next call of soundio_flush_events.

In other words: The library is basically unuseable on windows PCs without a microphone.

### PR DESCRIPTION
**Pull request by jacquesh**
Should fix #63 

I wasn't sure where to put the error define, but the other definitions are in the header so I just threw it in there.

### CODE REVIEW

File: src/wasapi.c [hunk 1]
```diff
@@ -666,40 +666,48 @@ static int refresh_devices(struct SoundIoPrivate *si) {
...
-        return SoundIoErrorOpeningDevice;
+        if(hr != E_NOTFOUND) {
+            deinit_refresh_devices(&rd);
+            return SoundIoErrorOpeningDevice;
+        }
     }
-    if ((err = from_lpwstr(rd.lpwstr, &rd.default_render_id, &rd.default_render_id_len))) {
-        deinit_refresh_devices(&rd);
-        return err;
+    if(rd.default_render_device) {
```
Comment (jacquesh) [inline src/wasapi.c]: The docs say that this is guaranteed to be null in the event that there isn't one but it might be cleared to have the same check as above (that hr != E_NOTFOUND).

**Comment by andrewrk** [comment]
Let's put the error define in wasapi.c, if you don't mind.

**Comment by andrewrk** [comment]
Other than that I think this is ready to be merged. Were you able to verify this fix on your computer?

**Comment by jacquesh** [comment]
Done. Yes I checked that it works. I can successfully get a devices_changed callback with 0 input devices (and 0 output devices for that matter...simultaneously, which was somewhat amusing).
